[build]
  base = "/"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_VERSION = "10.2.4"

[context.production]
  command = "pnpm run build"

[context.deploy-preview]
  command = "pnpm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "pnpm run build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "pnpm run build"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "pnpm dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

# Custom headers — https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file
[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "SAMEORIGIN"
    Cache-Control= '''
    public,
    max-age=31536000'''
